name: Comment on Merge

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "テスト \n テスト\n\nテスト \n\n テスト"
